// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.LegoArmWithEncoder;
    
import org.usfirst.frc100.LegoArmWithEncoder.devices.ParallaxContinuousRotationServo;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Victor;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static ParallaxContinuousRotationServo robotArmArmContinuousRotationServo;
    public static DigitalInput robotArmArmUpperLimit;
    public static DigitalInput robotArmArmLowerLimit;
    public static AnalogPotentiometer robotArmArmPositionPot;
    public static Victor driveTrainLeft;
    public static Victor driveTrainRight;
    public static AnalogInput driveTrainIRDistanceSensor;
    public static Relay clawClawActuatorRelay;
    public static DigitalInput robotArmEncoderA;
    public static DigitalInput robotArmEncoderB;
    public static DigitalInput robotArmEncoderIndex;
    
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        robotArmArmContinuousRotationServo = new ParallaxContinuousRotationServo(0);        
        robotArmArmUpperLimit = new DigitalInput(1);        
        robotArmArmLowerLimit = new DigitalInput(0);        
        robotArmArmPositionPot = new AnalogPotentiometer(0, 1.0, 0.0);
        robotArmEncoderA = new DigitalInput(2);
        robotArmEncoderB = new DigitalInput(3);
        robotArmEncoderIndex = new DigitalInput(4);
        
        driveTrainLeft = new Victor(3);     
        driveTrainRight = new Victor(2);
        driveTrainIRDistanceSensor = new AnalogInput(1);
        
        clawClawActuatorRelay = new Relay(0);
      

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
