// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2016.subsystems;

import org.usfirst.frc100.Robot2016.Robot;
import org.usfirst.frc100.Robot2016.RobotMap;
import org.usfirst.frc100.Robot2016.commands.*;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class MoveRollIn extends Subsystem {

    private final SpeedController pickUpRoller = RobotMap.moveRollInPickUpRoller;
    private final DigitalInput insideDetector = RobotMap.pickUpHomeLimit;
    boolean insideRobot = false;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());

    }

    public void setRollerSpeed(double speed){
/*
    	if(Robot.moveRollIn.hitDetector()){
    		if(Robot.oi.spinOut.get()){
    			pickUpRoller.set(-speed/2);
    		}else{
    			Robot.moveRollIn.stop();
    		}
    	}else{
    		pickUpRoller.set(speed);
    	}
    	*/
    	/*
    	if(RobotMap.pickUpInsideDetector.get()){
    		insideRobot = true;
    	}
    	else{
    		insideRobot = false;
    	}
    	if(insideRobot)
    	{
    		pickUpRoller.set(.5);
    	}
    	else
    	{
    		pickUpRoller.set(speed);
    	}
    	*/
    	if(!RobotMap.pickUpHomeLimit.get())
    	pickUpRoller.set(speed);
    	else
    	pickUpRoller.set(0);

    }
    public void moveRollerBack()
    {
    	pickUpRoller.set(-.4);
    }


    public void stop(){

    	pickUpRoller.set(0);

    }

    public boolean hitDetector(){

    	return insideDetector.get();

    }


}

