// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.SyntheticDriveTrain.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc100.SyntheticDriveTrain.Robot;
import org.usfirst.frc100.SyntheticDriveTrain.RobotMap;

import com.ctre.phoenix.motorcontrol.ControlMode;

/**
 *
 */
public class MotionMagicGo extends Command {
	public static boolean done;
	public static double setpoint;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public MotionMagicGo() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	done = false;
    	setpoint = 4000;
    	RobotMap.driveTrainRightMaster.set(ControlMode.MotionMagic, setpoint);
    	RobotMap.driveTrainLeftMaster.set(ControlMode.MotionMagic, setpoint);

    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(RobotMap.driveTrainRightMaster.getSelectedSensorPosition(0)<setpoint + 5 && RobotMap.driveTrainRightMaster.getSelectedSensorPosition(0)>setpoint - 5 
    	   && RobotMap.driveTrainLeftMaster.getSelectedSensorPosition(0)>setpoint - 5 && RobotMap.driveTrainLeftMaster.getSelectedSensorPosition(0)<setpoint + 5){
    		done = true;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return done;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
