// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2018;


import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc100.Robot2018.commands.*;
import org.usfirst.frc100.Robot2018.subsystems.*;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */


public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	//Defining the joystick buttons which each correspond to a command
    public JoystickButton button0;

    public JoystickButton button1;
    public JoystickButton button2;
    public JoystickButton button3;
    public JoystickButton button4;
    public JoystickButton button5;
    public JoystickButton button6;
    public JoystickButton button7;
    public JoystickButton button8;
    public JoystickButton button9;
    public JoystickButton button10;
    public JoystickButton button11;
    public JoystickButton button12;
    public JoystickButton rightS; 
    public JoystickButton buttona;
    public JoystickButton buttonb;  
    public JoystickButton BS; 
    public JoystickButton BR; 
    public JoystickButton leftS;
    public JoystickButton updatePrefs;
    
    // defining the joysticks that the buttons are on(dual actions)
    public static Joystick leftController;
    public static Joystick rightStick;

    //deifing the auto selector
    public Joystick autoModeSelect;
    //defining the operator contoller(the logitech controller)
    public static Joystick operator;
    //shifing button for the shifting command.
    public static JoystickButton shiftoff;
    //auto selector buttons
    public JoystickButton binary1;
 	public JoystickButton binary2;
 	public JoystickButton binary3;
 	public JoystickButton binary4;

	private Button buttonneg;



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	SmartDashboard.putBoolean("LOADED", false); //This has NOT been added to the UpdateSmartDashboard due to its purpose
        // I THINK THAT THIS IS THE CORRECT JOYSTICK SETUP AS WITH THE OI LIST @ http://bit.ly/2FX9ycl                      -Alex B
    	//telling the roborio which port the controller is plugged into( the value can be 0-n n= the number of port on the computer)
    	operator = new Joystick(2);//port 2
        autoModeSelect = new Joystick(3);//port 3
        rightStick = new Joystick(1);//port 1
        leftController = new Joystick(0);//port 0
        //telling the roborio which joystick its on and value of the button on the controller(1-buttons on each controller)
        //the parameters are: (joystick name, button value
        binary1 = new JoystickButton(autoModeSelect, 1);//these correspond to a value on the autonomous selector (0-15
      	binary2 = new JoystickButton(autoModeSelect, 2);
      	binary3 = new JoystickButton(autoModeSelect, 3);
      	binary4 = new JoystickButton(autoModeSelect, 4);
        button12 = new JoystickButton(operator, 2);
        //have the button followed by a while held and a command in it's param will call a command when it is held
        button12.whileHeld(new WinchWind());
        
        button11 = new JoystickButton(operator, 1);
        button11.whileHeld(new toggleElevatorSpeed());
        button9 = new JoystickButton(rightStick, 1);
        //when pressed will run the command when a button is pressed
        button9.whenPressed(new IntakeOut());
        button7 = new JoystickButton(leftController, 1);
        button7.whileHeld(new IntakeIn());
        button6 = new JoystickButton(operator, 6);
        button6.whenPressed(new ElevatorUp());
        button5 = new JoystickButton(operator, 8);
        button5.whenPressed(new ElevatorDown());
        button3 = new JoystickButton(rightStick, 3); 
        button3.whenPressed(new shiftOff());
        button2 = new JoystickButton(leftController, 3);
        button2.whenPressed(new shift());
        rightS = new JoystickButton(operator, 4);
        rightS.whenPressed(new ElevatorArmUp());
        button0 = new JoystickButton(leftController, 8);
        button0.whenPressed(new ParserCommandVer());
        buttonneg = new JoystickButton(leftController, 9);
        buttonneg.whenPressed(new GoToCube());


        // SmartDashboard Buttons
        new UpdateSmartDashboard();
        //these command are autogenerated but mostly useless unless you are running commands without buttons and want to run them from the smartdashboard
        SmartDashboard.putData(" WinchWind", new WinchWind());
        SmartDashboard.putData("Create Path", new PathFindingLogicCode());


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLeftController() {
        return leftController;
    }

    public Joystick getRightStick() {
        return rightStick;
    }
    public int selector() {
    	//how the autoselector get the value
		boolean bin1Val = binary1.get();
		boolean bin2Val = binary2.get();
		boolean bin3Val = binary3.get();
		boolean bin4Val = binary4.get();
		int total = 0;

		if (bin1Val) {
			total += 1;
		}
		if (bin2Val) {
			total += 2;
		}
		if (bin3Val) {
			total += 4;
		}
		if (bin4Val) {
			total += 8;
		}
		return total;
	}
    //an autogenerated command that recieves the values for the ROBORIO
    public Joystick getAutoModeSelect() {
        return autoModeSelect;
    }

    public Joystick getOperator() {
        return operator;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

