// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2018;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

//import org.usfirst.frc100.RandomTest.RobotMap;
import org.usfirst.frc100.Robot2018.commands.*;
import org.usfirst.frc100.Robot2018.subsystems.*;


import java.util.*;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.kauailabs.navx.frc.AHRS;

import java.util.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
                                                                                                                                                                                                                                                                  
    public static SendableChooser<Command> chooser = new SendableChooser<>();
    public static boolean MaunalDuo;
	public static Boolean logitech;
	public static Boolean TankDrive;
	public static double RequestedTime;

	public static Boolean Logitech;
	public static Boolean ArcadeDrive;

    public static OI oi;

    
    //System.out.println("INITALIZED =======================================================================================");
    public static Preferences prefs = Preferences.getInstance(); //Creates preferences object

    double P; 
    double I; 
    double D; 
    double F;
    double time;
    double PL; 
    double IL; 
    double DL;
    double FL;


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DriveTrain driveTrain;
    public static Elevator elevator;
    public static ElevatorArm elevatorArm;
    public static Intake intake;
    public static ClimbingArm climbingArm;
    public static Winch winch;
    public static Misc misc;
    public static DoubleSolen DoubleSolen;
    public static String gameData;
    public static double EP;
    public static double EI;
    public static double ED;
    public static double EF;
    public static AHRS ahrs; 
  

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
    	
    	SmartDashboard.putBoolean("EnteredTestPathFinding", false);
    	SmartDashboard.putBoolean("PathFindingParsing", false);
    	SmartDashboard.putBoolean("SetControlMode", false);
        RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrain = new DriveTrain();
        elevator = new Elevator();
        elevatorArm = new ElevatorArm();
        intake = new Intake();
        climbingArm = new ClimbingArm();
        winch = new Winch();
        misc = new Misc();
        DoubleSolen = new DoubleSolen();
       /* RobotMap.elevatorElevatorTalon.configClosedloopRamp(1, 0);
        RobotMap.elevatorElevatorTalon.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 0);
        RobotMap.elevatorElevatorTalon.selectProfileSlot(0, 0);
        RobotMap.elevatorElevatorTalon.config_kP(0, 0, 0);
        RobotMap.elevatorElevatorTalon.config_kI(0, 0, 0);
        RobotMap.elevatorElevatorTalon.config_kD(0, 0, 0);
        RobotMap.elevatorElevatorTalon.config_kF(0, 0, 0);
        RobotMap.elevatorElevatorTalon.setInverted(true);
        RobotMap.elevatorElevatorTalon.setSensorPhase(true);
        RobotMap.elevatorElevatorTalon.configNominalOutputForward(0.0f, 0);
        RobotMap.elevatorElevatorTalon.configNominalOutputReverse(0.0f, 0);
        RobotMap.elevatorElevatorTalon.configMotionAcceleration(150, 0);
        RobotMap.elevatorElevatorTalon.configMotionCruiseVelocity(100, 0);
        RobotMap.elevatorElevatorTalon.configPeakOutputForward(25, 0);        /// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        RobotMap.elevatorElevatorVictor.configPeakOutputForward(25, 0);        /// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        RobotMap.elevatorElevatorVictor2.configPeakOutputForward(25, 0);        /// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
*/
        try {
			/***********************************************************************
			 * navX-MXP:
			 * - Communication via RoboRIO MXP (SPI, I2C, TTL UART) and USB.            
			 * - See http://navx-mxp.kauailabs.com/guidance/selecting-an-interface.
			 * 
			 * navX-Micro:
			 * - Communication via I2C (RoboRIO MXP or Onboard) and USB.
			 * - See http://navx-micro.kauailabs.com/guidance/selecting-an-interface.
			 * 
			 * Multiple navX-model devices on a single robot are supported.
			 ************************************************************************/
            //ahrs = new AHRS(SerialPort.Port.kUSB1);
            //ahrs = new AHRS(SerialPort.Port.kMXP, SerialDataType.kProcessedData, (byte)200);
            //ahrs = new AHRS(SPI.Port.kMXP);
            ahrs = new AHRS(I2C.Port.kOnboard); // Uses onboard I2C port
        	//ahrs.enableLogging(true); // Sends debugging logging
        } catch (RuntimeException ex ) {
            DriverStation.reportError("Error instantiating navX  MXP:  " + ex.getMessage(), true);
        }
        
       
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        chooser.addDefault("Autonomous Command", new AutonomousCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        new UpdateSmartDashboard();
        //SmartDashboard.putData("Auto mode", chooser);
        
        new UpdateSmartDashboard();

        SmartDashboard.putData("Auto mode", chooser);
       // SmartDashboard.putData("TestPath", new PathFindingLogicCode());
        
       // SmartDashboard.putData("JSON", new ParseJSONFile());



        logitech= false;
        TankDrive= false;
        prefs = Preferences.getInstance();
        prefs.putDouble("Number of Seconds to Wait", 10);
        prefs.putBoolean("TankDrive", false);
        prefs.putBoolean("Solenoid Maunal", false);
		prefs.putBoolean("DriverStation", false);
        Logitech = false;
        ArcadeDrive = true;
        prefs = Preferences.getInstance();
        prefs.putBoolean("ArcadeDrive", true);
		prefs.putBoolean("Logitech", false);

        if (!prefs.containsKey("P")) {
        	prefs.putDouble("P", 0.01);
        }
        if (!prefs.containsKey("I")) {
        	prefs.putDouble("I", 0);
        }
        if (!prefs.containsKey("D")) {
        	prefs.putDouble("D", 0);
        }
        if (!prefs.containsKey("F")) {
        	prefs.putDouble("F", 0);
        }
        
        if (!prefs.containsKey("PL")) {
        	prefs.putDouble("PL", 0.01);
        }
        if (!prefs.containsKey("IL")) {
        	prefs.putDouble("IL", 0);
        }
        if (!prefs.containsKey("DL")) {
        	prefs.putDouble("DL", 0);
        }
        if (!prefs.containsKey("F")) {
        	prefs.putDouble("F", 0.3);
        }
        if (!prefs.containsKey("FL")) {

        	prefs.putDouble("FL", 0.3);
        }
        if (!prefs.containsKey("EP")) {
        	prefs.putDouble("EP", 0.01);
        }
        if (!prefs.containsKey("EI")) {
        	prefs.putDouble("EI", 0);
        }
        if (!prefs.containsKey("ED")) {
        	prefs.putDouble("ED", 0);
        }
        if (!prefs.containsKey("EF")) {
        	prefs.putDouble("EF", 0);
        }
        
        //new ParseJSONFile();
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {

    	
    	

        //autonomousCommand = chooser.getSelected();
        // schedule the autonomous command (example)
       // if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
    	 ahrs.reset();
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        EP= prefs.getDouble("EP", 0);
    	EI= prefs.getDouble("EI", 0);
    	ED= prefs.getDouble("ED", 0);
    	EF= prefs.getDouble("EF", 0);
        RobotMap.elevatorElevatorTalon.configClosedloopRamp(1, 0);
        RobotMap.elevatorElevatorTalon.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 0);
        RobotMap.elevatorElevatorTalon.selectProfileSlot(0, 0);
        RobotMap.elevatorElevatorTalon.config_kP(0, EP, 0);
        RobotMap.elevatorElevatorTalon.config_kI(0, EI, 0);
        RobotMap.elevatorElevatorTalon.config_kD(0, ED, 0);
        RobotMap.elevatorElevatorTalon.config_kF(0, EF, 0);
        RobotMap.elevatorElevatorTalon.configNominalOutputForward(0.0f, 0);
        RobotMap.elevatorElevatorTalon.configNominalOutputReverse(0.0f, 0);
        RobotMap.elevatorElevatorTalon.configMotionAcceleration(25, 0);
        RobotMap.elevatorElevatorTalon.configMotionCruiseVelocity(50, 0);
        RobotMap.elevatorElevatorTalon.configPeakOutputForward(25, 0);  
        RobotMap.elevatorElevatorTalon.setSensorPhase(true);

        
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
    	EP= prefs.getDouble("EP", 1);
    	EI= prefs.getDouble("EI", 0);
    	ED= prefs.getDouble("ED", 0);
    	EF= prefs.getDouble("EF", 0);
    	//System.out.println("running");
        //SmartDashboard.putData("TestPath", new PathFindingLogicCode());
        //SmartDashboard.putData("Henry test path", new PathFinding());
        RequestedTime = prefs.getDouble("Number of Seconds to Wait", 10);
        logitech = prefs.getBoolean("DriverStation", false);
        TankDrive = prefs.getBoolean("TankDrive", false);
        MaunalDuo = prefs.getBoolean("Solenoid Maunal", false);
        SmartDashboard.putBoolean("TankDrive On", TankDrive);
        SmartDashboard.putBoolean("DriverStation On", logitech);
        SmartDashboard.putBoolean("solenoid On", RobotMap.driveTrainShiftingSolenoid.get());
        Scheduler.getInstance().run();
        /*if(OI.leftController.getRawButton(1)){
        	RobotMap.driveTrainShiftingSolenoid.set(true);
        }else if(OI.rightStick.getRawButton(1)) {
        	
        	RobotMap.driveTrainShiftingSolenoid.set(false);
        }else if(OI.operator.getRawButtonPressed(1)) {
        	RobotMap.driveTrainShiftingSolenoid.set(true);
        }else if(OI.operator.getRawButtonPressed(2)) {
        }*/
        RobotMap.elevatorElevatorTalon.set(ControlMode.PercentOutput, -OI.operator.getRawAxis(3));
        Logitech = prefs.getBoolean("Logitech", false);
        ArcadeDrive = prefs.getBoolean("ArcadeDrive", false);
        SmartDashboard.putBoolean("ArcadeDrive On", ArcadeDrive);
        SmartDashboard.putBoolean("Logitech On", Logitech);
        SmartDashboard.putNumber("velR", (RobotMap.driveTrainRightMaster.getSelectedSensorVelocity(0)/1508.965) * 3.28);///4096/1.5);
        SmartDashboard.putNumber("velL", (RobotMap.driveTrainLeftMaster.getSelectedSensorVelocity(0)/1508.965) *3.28);
        SmartDashboard.putBoolean("solenoid On", RobotMap.driveTrainShiftingSolenoid.get());
        Scheduler.getInstance().run();
        SmartDashboard.putNumber("OutPercent", RobotMap.elevatorElevatorTalon.getMotorOutputPercent());
        SmartDashboard.putNumber("error", RobotMap.elevatorElevatorTalon.getClosedLoopError(0));
        SmartDashboard.putNumber("Position", RobotMap.elevatorElevatorTalon.getSelectedSensorPosition(0));
        SmartDashboard.putNumber("velocity", RobotMap.elevatorElevatorTalon.getSelectedSensorVelocity(0));


        if(OI.operator.getRawButtonPressed(1)){
        	RobotMap.elevatorElevatorTalon.setSelectedSensorPosition(0, 0, 0);
        }

        //Scheduler.getInstance().run();

    }
}
