// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.SethMotionMagic;

import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc100.SethMotionMagic.commands.*;
import org.usfirst.frc100.SethMotionMagic.subsystems.*;

import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
    SendableChooser<Command> chooser = new SendableChooser<>();
	public static double positionSetpoint;
    public static TalonSRX talon;
    public static Preferences prefs;
    public static OI oi;
    public static double p;
    public static double i;
    public static double d;
    public static double f;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static MotionMotor motionMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        motionMotor = new MotionMotor();
        talon = RobotMap.motionMotorTalonSRX;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();
        
        prefs = Preferences.getInstance();
        prefs.putDouble("P", 5);
        prefs.putDouble("I", 0.01);
        prefs.putDouble("D", 1);
        prefs.putDouble("F", 0.5);
        prefs.putDouble("Setpoint", 4000);

        talon.configClosedloopRamp(1, 0);
        talon.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 0);
        talon.selectProfileSlot(0, 0);
        talon.config_kP(0, 0, 0);
        talon.config_kI(0, 0, 0);
        talon.config_kD(0, 0, 0);
        talon.config_kF(0, 0, 0);
        talon.setInverted(true);
        talon.setSensorPhase(true);
        talon.configNominalOutputForward(0.0f, 0);
        talon.configNominalOutputReverse(0.0f, 0);
        talon.configMotionAcceleration(150, 0);
        talon.configMotionCruiseVelocity(100, 0);
        
        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        chooser.addDefault("Autonomous Command", new AutonomousCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        SmartDashboard.putData("Auto mode", chooser);
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
        autonomousCommand = chooser.getSelected();
        // schedule the autonomous command (example)
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        p = prefs.getDouble("P", 0);
        i = prefs.getDouble("I", 0);
        d = prefs.getDouble("D", 0);
        f = prefs.getDouble("F", 0);
        talon.config_kP(0, p, 0);
        talon.config_kI(0, i, 0);
        talon.config_kD(0, d, 0);
        talon.config_kF(0, f, 0);
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        positionSetpoint = prefs.getDouble("Setpoint", 0);
        SmartDashboard.putNumber("encoderValue", talon.getSelectedSensorPosition(0));
        
    }
}
