// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.BALLista.subsystems;

import org.usfirst.frc100.BALLista.RobotMap;
import org.usfirst.frc100.BALLista.commands.*;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LoaderPinball extends Subsystem {

    private final DigitalInput loaded = RobotMap.loaderPinballLoaded;
    private final DoubleSolenoid ballHandlerSolenoid1 = RobotMap.loaderPinballBallHandlerSolenoid1;
    private final DoubleSolenoid ballHandlerSolenoid2 = RobotMap.loaderPinballBallHandlerSolenoid2;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {

    }

}

