// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.Robot2.commands;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc0.Robot2.Robot;
import org.usfirst.frc0.Robot2.RobotMap;
import org.usfirst.frc0.Robot2.subsystems.DriveTrain;

/**
 *
 */
public class  TankDrive extends Command {
	//Ultrasonic ultra = new Ultrasonic(1,1);
	int angle = 75;
	String left = "go Left!";
	String onTrac = "good!";
	String right = "goRight";
	
	
    public TankDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	// ultra.setAutomaticMode(true);
    	
    }
    
   
   
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//AnalogInput stuff = RobotMap.lineFollower;
    	Robot.driveTrain.tankIt(Robot.oi.joystick1);
    	SmartDashboard.putNumber("voltage range ", RobotMap.rangeFinder.getVoltage());
    	//RobotMap.exampleServo.setAngle(angle);
    	//SmartDashboard.putNumber("Info",RobotMap.lineFollower.getVoltage());
    	//if(RobotMap.lineFollower.getVoltage() < 4.0)
    
    	//{
    	//	SmartDashboard.putString("direction", "c");
    		
    //	}
    	//else
    	//{
    		///.putString("direction","l");
    		
    //	}
    	/*
    	if(RobotMap.lineFollowerLeft.getVoltage() < 3)
    	{
    		SmartDashboard.putString("direction", right);
    	}
    	if(RobotMap.lineFollowerRight.getVoltage() < 3)
    	{
    		SmartDashboard.putString("direction", left);
    	}
    	*/
    	 
    	 }
    
    		
    	
    

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
