// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2017.subsystems;

import org.usfirst.frc100.Robot2017.Robot;
import org.usfirst.frc100.Robot2017.RobotMap;
import org.usfirst.frc100.Robot2017.commands.*;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class DriveTrain extends Subsystem {
	
	/*
    private final SpeedController leftMotor = RobotMap.driveTrainleftMotor;
    private final SpeedController rightMotor = RobotMap.driveTrainrightMotor;
    private final RobotDrive drive = RobotMap.driveTraindrive;
    private final Encoder leftEncoder = RobotMap.driveTrainleftEncoder;
    private final Encoder rightEncoder = RobotMap.driveTrainrightEncoder;
    private final Solenoid leftShifter = RobotMap.driveTrainleftShifter;
    private final Solenoid rightShifter = RobotMap.driveTrainrightShifter;
    private final AnalogGyro digialGyroUno = RobotMap.driveTraindigialGyroUno;
    private final Ultrasonic ultraSanic = RobotMap.driveTrainultraSanic;
    */
	
	public final Solenoid driveTrainShifter = RobotMap.driveTrainShifter;
	
	public final Encoder driveTrainLeftEncoder = RobotMap.driveTrainLeftEncoder;
	public final Encoder driveTrainRightEncoder = RobotMap.driveTrainRightEncoder;

	private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
	
	public final ADXRS450_Gyro gyro = RobotMap.gyro;
	
    public double angle; 

    public void initDefaultCommand() {
        setDefaultCommand(new TankDrive()); 
    }
    
    public void updateDashboard() {
		SmartDashboard.putNumber("DriveTrain/Left Encoder Raw", driveTrainLeftEncoder.getRaw());
		SmartDashboard.putNumber("DriveTrain/Left Encoder Count", driveTrainLeftEncoder.get());
		SmartDashboard.putNumber("DriveTrain/Left Encoder Distance", driveTrainLeftEncoder.getDistance());
    	SmartDashboard.putNumber("DriveTrain/Left Encoder Rate", driveTrainLeftEncoder.getRate());
		
		SmartDashboard.putNumber("DriveTrain/Right Encoder Raw", driveTrainRightEncoder.getRaw());
		SmartDashboard.putNumber("DriveTrain/Right Encoder Count", driveTrainRightEncoder.get());
		SmartDashboard.putNumber("DriveTrain/Right Encoder Distance", driveTrainRightEncoder.getDistance());
		SmartDashboard.putNumber("DriveTrain/Right Encoder Rate", driveTrainRightEncoder.getRate());

    	SmartDashboard.putNumber("DriveTrain/DifferenceOfEncodersDistance:", Math.abs(driveTrainRightEncoder.getDistance() - driveTrainLeftEncoder.getDistance()));
		SmartDashboard.putNumber("DriveTrain/DifferenceOfEncodersRate:", Math.abs(driveTrainRightEncoder.getRate() - driveTrainLeftEncoder.getRate()));
		
		SmartDashboard.putNumber("DriveTrain/Gyro Angle", gyro.getAngle());
		
		SmartDashboard.putBoolean("DriveTrain/DriveTrainShifter state", driveTrainShifter.get());
	}
    
    public void driveRobot(Joystick joy, Joystick joy2){
    	robotDrive.tankDrive(joy.getRawAxis(1), -joy2.getRawAxis(1));
    }

    public void stop(){
    	robotDrive.tankDrive(0, 0);
    }
    
    public boolean isDriveTrainShifterOpen(){
    	return driveTrainShifter.get();
    }
    
    public void setDriveTrainShifter(boolean open){
    	if(open){
    		driveTrainShifter.set(open);
    	}else{
    		driveTrainShifter.set(!open);
    	}
    }
}


