// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2017.subsystems;

import org.usfirst.frc100.Robot2017.RobotMap;
import org.usfirst.frc100.Robot2017.commands.*;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearMech extends Subsystem {
	
	public final DoubleSolenoid gearMechDrop = RobotMap.gearMechDrop;
    public final DoubleSolenoid gearMechFlap = RobotMap.gearMechFlap;
    public final DoubleSolenoid gearMechLift = RobotMap.dumperLift;

    public void initDefaultCommand() {

    }
    
    public boolean isGearMechDropClosed(){
    	return gearMechLift.get() == DoubleSolenoid.Value.kForward;
    }
    
    public void setGearMechDrop(boolean closed) {
    	if(!closed){
    		gearMechLift.set(DoubleSolenoid.Value.kReverse);
		}else{
			gearMechLift.set(DoubleSolenoid.Value.kForward);

		}
	}
    
    public boolean isGearMechFlapClosed(){
    	return gearMechFlap.get() == DoubleSolenoid.Value.kForward;
    }
    
    public void setGearMechFlap(boolean closed) {
    	if(!closed){
    		gearMechFlap.set(DoubleSolenoid.Value.kReverse);
		}else{
			gearMechFlap.set(DoubleSolenoid.Value.kForward);

		}
	}
    
    public boolean isGearMechLiftClosed(){
    	return gearMechLift.get() == DoubleSolenoid.Value.kForward;
    }
    
    public void setGearMechLift(boolean closed) {
    	if(!closed){
    		gearMechLift.set(DoubleSolenoid.Value.kReverse);
		}else{
			gearMechLift.set(DoubleSolenoid.Value.kForward);

		}
	}
}


