// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2017.subsystems;

import org.usfirst.frc100.Robot2017.RobotMap;
import org.usfirst.frc100.Robot2017.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Intake extends Subsystem {
	/*
    private final SpeedController outsideRoller = RobotMap.intakeoutsideRoller;
    private final SpeedController hopperRoller = RobotMap.intakehopperRoller;
    private final SpeedController beltRoller = RobotMap.intakebeltRoller;
    private final DigitalInput ballSensor = RobotMap.intakeballSensor;
	*/
    public void initDefaultCommand() {

    }

	public void updateDashboard() {
		SmartDashboard.putNumber("Intake/OutsideRoller: ", outsideRoller.get());
		SmartDashboard.putNumber("Intake/HopperRoller: ", hopperRoller.get());
		SmartDashboard.putNumber("Intake/BeltRoller: ", beltRoller.get());
		SmartDashboard.putBoolean("Intake/BallSensor: ", ballSensor.get());
	}
}


