// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc100.Robot2017.subsystems;

import org.usfirst.frc100.Robot2017.RobotMap;
import org.usfirst.frc100.Robot2017.commands.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Shooter extends Subsystem {

    
    //private final SpeedController moter = RobotMap.shootermoter;
    //private final Encoder incoder = RobotMap.shooterincoder;

    public void updateDashboard(){
    	//SmartDashboard.putNumber("Shooter Encoder Value", incoder.getRate()); 
    }
    public void initDefaultCommand() {
       
    }
    
    public void setShooterSpeed(double speed){
    	//moter.set(speed); 
    }
    
    public void stop(){
    	//moter.set(0);
    }

	public void updateDashboard() {
		// TODO Auto-generated method stub
		SmartDashboard.putNumber("Shooter/Motor: ", moter.get());
		SmartDashboard.putNumber("Shooter/Encoder Rate: ", incoder.getRate());
		SmartDashboard.putNumber("Shooter/Encoder Distance: ", incoder.getDistance());
		SmartDashboard.putNumber("Shooter/Encoder Count: ", incoder.get());
		
	}
}


