// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
/**
 * Example demonstrating the motion magic control mode.
 * Tested with Logitech F710 USB Gamepad inserted into Driver Station.
 * 
 * Be sure to select the correct feedback sensor using SetFeedbackDevice() below.
 *
 * After deploying/debugging this to your RIO, first use the left Y-stick 
 * to throttle the Talon manually.  This will confirm your hardware setup/sensors
 * and will allow you to take initial measurements.
 * 
 * Be sure to confirm that when the Talon is driving forward (green) the 
 * position sensor is moving in a positive direction.  If this is not the 
 * cause, flip the boolean input to the reverseSensor() call below.
 *
 * Once you've ensured your feedback device is in-phase with the motor,
 * and followed the walk-through in the Talon SRX Software Reference Manual,
 * use button1 to motion-magic servo to target position specified by the gamepad stick.
 */

package org.usfirst.frc0.MyRobot;

import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import java.util.concurrent.TimeUnit;

import org.usfirst.frc0.MyRobot.commands.*;
import org.usfirst.frc0.MyRobot.subsystems.*;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.StatusFrameEnhanced;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
    SendableChooser<Command> chooser = new SendableChooser<>();
	public static Preferences prefs;
	public static double PIDmotor12;
    public static OI oi;
    StringBuilder _sb = new StringBuilder();
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static PIDDriveTrain pIDDriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pIDDriveTrain = new PIDDriveTrain();
        prefs = Preferences.getInstance();
        /* 
		RobotMap.pIDDriveTrainTalonSRX1.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Absolute, Constants.kPIDLoopIdx, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.setSensorPhase(true);
		RobotMap.pIDDriveTrainTalonSRX1.setInverted(false);
		
		RobotMap.pIDDriveTrainTalonSRX1.setStatusFramePeriod(StatusFrameEnhanced.Status_13_Base_PIDF0, 10, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.setStatusFramePeriod(StatusFrameEnhanced.Status_10_MotionMagic, 10, Constants.kTimeoutMs);

		RobotMap.pIDDriveTrainTalonSRX1.configNominalOutputForward(0, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.configNominalOutputReverse(0, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.configPeakOutputForward(1, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.configPeakOutputReverse(-1, Constants.kTimeoutMs);
		
		RobotMap.pIDDriveTrainTalonSRX1.selectProfileSlot(Constants.kSlotIdx, Constants.kPIDLoopIdx);
		RobotMap.pIDDriveTrainTalonSRX1.config_kF(0, 0.2, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.config_kP(0, 0.2, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.config_kI(0, 0, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.config_kD(0, 0, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.configMotionCruiseVelocity(15000, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.configMotionAcceleration(6000, Constants.kTimeoutMs);
		RobotMap.pIDDriveTrainTalonSRX1.setSelectedSensorPosition(0, Constants.kPIDLoopIdx, Constants.kTimeoutMs);*/
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        chooser.addDefault("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        SmartDashboard.putData("Auto mode", chooser);
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
        autonomousCommand = chooser.getSelected();
        // schedule the autonomous command (example)
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        SmartDashboard.putNumber("Encoder", RobotMap.pIDDriveTrainTalonSRX1.getSelectedSensorPosition(0));
        SmartDashboard.putNumber("EncoderSpeed", RobotMap.pIDDriveTrainTalonSRX1.getSelectedSensorVelocity(0));

        SmartDashboard.putNumber("Encoder2", RobotMap.pIDDriveTrainTalonSRX2.getSelectedSensorPosition(0));
        SmartDashboard.putString("Up One", "Button 1(X) Value: 1000");
        SmartDashboard.putString("Up Two", "Button 2(A) Value: 100");
        SmartDashboard.putString("Up Three", "Button 3(B) Value: 5000");

      /*//SmartDashboard.putNumber("MotorPIDNumber", PIDmotor1);
        SmartDashboard.putBoolean("UpOne", UpOne.upOne);
		double leftYstick = -1.0 * OI.joystick1.getY();
		double motorOutput = RobotMap.pIDDriveTrainTalonSRX1.getMotorOutputPercent();
		_sb.append("\tOut%:");
		_sb.append(motorOutput);
		_sb.append("\tVel:");
		_sb.append(RobotMap.pIDDriveTrainTalonSRX1.getSelectedSensorVelocity(Constants.kPIDLoopIdx));

		if (OI.joystick1.getRawButton(1)) {
			double targetPos = leftYstick * 1680 * 10.0;
			RobotMap.pIDDriveTrainTalonSRX1.set(ControlMode.MotionMagic, 10000); 

			_sb.append("\terr:");
			_sb.append(RobotMap.pIDDriveTrainTalonSRX1.getClosedLoopError(Constants.kPIDLoopIdx));
			_sb.append("\ttrg:");
			_sb.append(targetPos);
		} else {
			RobotMap.pIDDriveTrainTalonSRX1.set(ControlMode.PercentOutput, leftYstick);
		}
		Instrum.Process(RobotMap.pIDDriveTrainTalonSRX1, _sb);
		try { TimeUnit.MILLISECONDS.sleep(10); } catch(Exception e) {}*/
    }
}
